create table if not exists public.content (
  id text primary key,
  region_slug text not null,
  github_issue_number bigint unique,
  status text not null check (status in ('published', 'withdrawn')),
  title text not null,
  summary text,
  nickname text,
  markdown text,
  external_url text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint content_published_at_required check (
    status = 'withdrawn' or published_at is not null
  )
);

create index if not exists content_public_region_idx
  on public.content (region_slug, published_at desc, id asc)
  where status = 'published';

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  label text not null,
  normalized text not null unique
);

create table if not exists public.content_tags (
  content_id text not null references public.content(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (content_id, tag_id)
);

create table if not exists public.moderation_events (
  delivery_id text primary key,
  github_issue_number bigint not null,
  event_name text not null,
  applied_at timestamptz not null default now()
);

create index if not exists moderation_events_issue_idx
  on public.moderation_events (github_issue_number, applied_at desc);

create table if not exists public.submission_fingerprints (
  fingerprint text primary key,
  source_hash text not null,
  state text not null check (state in ('reserved', 'submitted')),
  reserved_until timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists submission_fingerprints_expiry_idx
  on public.submission_fingerprints (reserved_until);

create table if not exists public.successful_submission_events (
  id bigint generated by default as identity primary key,
  source_hash text not null,
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create index if not exists successful_submission_events_source_idx
  on public.successful_submission_events (source_hash, created_at desc);

alter table public.content enable row level security;
alter table public.tags enable row level security;
alter table public.content_tags enable row level security;
alter table public.moderation_events enable row level security;
alter table public.submission_fingerprints enable row level security;
alter table public.successful_submission_events enable row level security;
