create table if not exists public.content (
  id text primary key,
  region_slug text not null,
  github_issue_number bigint unique,
  status text not null check (status in ('published', 'withdrawn')),
  title text not null,
  summary text,
  nickname text,
  markdown text,
  external_url text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint content_published_at_required check (
    status = 'withdrawn' or published_at is not null
  )
);

create index if not exists content_public_region_idx
  on public.content (region_slug, published_at desc, id asc)
  where status = 'published';

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  label text not null,
  normalized text not null unique
);

create table if not exists public.content_tags (
  content_id text not null references public.content(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (content_id, tag_id)
);

create table if not exists public.moderation_events (
  delivery_id text primary key,
  github_issue_number bigint not null,
  event_name text not null,
  applied_at timestamptz not null default now()
);

create index if not exists moderation_events_issue_idx
  on public.moderation_events (github_issue_number, applied_at desc);

create table if not exists public.submission_fingerprints (
  fingerprint text primary key,
  source_hash text not null,
  state text not null check (state in ('reserved', 'submitted')),
  reserved_until timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists submission_fingerprints_expiry_idx
  on public.submission_fingerprints (reserved_until);

create table if not exists public.successful_submission_events (
  id bigint generated by default as identity primary key,
  source_hash text not null,
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create index if not exists successful_submission_events_source_idx
  on public.successful_submission_events (source_hash, created_at desc);

create or replace function public.reserve_submission(
  p_source_hash text,
  p_fingerprint text,
  p_now timestamptz default now()
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  active_reservations integer;
  recent_successes integer;
begin
  delete from public.submission_fingerprints
  where reserved_until <= p_now;

  delete from public.successful_submission_events
  where created_at <= p_now - interval '1 hour';

  select count(*) into recent_successes
  from public.successful_submission_events
  where source_hash = p_source_hash
    and created_at > p_now - interval '1 hour';

  select count(*) into active_reservations
  from public.submission_fingerprints
  where source_hash = p_source_hash
    and state = 'reserved'
    and reserved_until > p_now;

  if recent_successes + active_reservations >= 10 then
    return 'rate_limit';
  end if;

  insert into public.submission_fingerprints (
    fingerprint,
    source_hash,
    state,
    reserved_until,
    created_at
  )
  values (
    p_fingerprint,
    p_source_hash,
    'reserved',
    p_now + interval '5 minutes',
    p_now
  );

  return 'reserved';
exception
  when unique_violation then
    return 'duplicate';
end;
$$;

create or replace function public.record_submission_success(
  p_fingerprint text,
  p_now timestamptz default now()
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation_source_hash text;
begin
  update public.submission_fingerprints
  set state = 'submitted',
      reserved_until = p_now + interval '24 hours'
  where fingerprint = p_fingerprint
    and state = 'reserved'
    and reserved_until > p_now
  returning source_hash into reservation_source_hash;

  if reservation_source_hash is null then
    return 'invalid_reservation';
  end if;

  insert into public.successful_submission_events (
    source_hash,
    fingerprint,
    created_at
  )
  values (
    reservation_source_hash,
    p_fingerprint,
    p_now
  );

  return 'submitted';
end;
$$;

revoke execute on function public.reserve_submission(text, text, timestamptz)
  from public, anon, authenticated;
revoke execute on function public.record_submission_success(text, timestamptz)
  from public, anon, authenticated;

grant execute on function public.reserve_submission(text, text, timestamptz)
  to service_role;
grant execute on function public.record_submission_success(text, timestamptz)
  to service_role;

alter table public.content enable row level security;
alter table public.tags enable row level security;
alter table public.content_tags enable row level security;
alter table public.moderation_events enable row level security;
alter table public.submission_fingerprints enable row level security;
alter table public.successful_submission_events enable row level security;
